let carta = false;
do {
  carta = Number(prompt("TAROTISTA: Piensa una pregunta e ingresa un numero del 1 al 22 para saber tu suerte o 0 para salir"));
  if (carta === 1) alert("El loco: Estás a punto de embarcarte en un nuevo viaje lleno de sorpresas y desafíos. Sé abierto a lo inesperado y confía en tu intuición. Puedes encontrar algunos riesgos u obstáculos en el camino, pero son parte de tu proceso de aprendizaje. Disfruta de la aventura y no tengas miedo de ser tú mismo.");
  else if (carta === 2) alert("El mago: Tienes el poder y las habilidades para manifestar tus deseos y lograr tus objetivos. Eres confiado y creativo, y sabes cómo usar tus recursos sabiamente. Tienes una visión clara de lo que quieres y cómo conseguirlo. Usa tus talentos y habilidades para hacer que las cosas sucedan.");
  else if (carta === 3) alert("La sacerdotisa: Estás en sintonía con tu sabiduría e intuición internas. Tienes acceso a un nivel más profundo de conocimiento y comprensión que otros pueden no ver. Eres tranquilo y sereno, y sabes cómo escuchar tu voz interior. Puedes necesitar un tiempo a solas para meditar y reflexionar sobre tu situación.");
  else if (carta === 4) alert("La emperatriz: Estás en un estado de abundancia y fertilidad. Eres protector y cariñoso, y tienes una fuerte conexión con la naturaleza y la vida. Eres creativo y expresivo, y tienes muchas ideas y proyectos que compartir con el mundo. También puedes experimentar algún crecimiento o expansión en tu vida personal o profesional.");
  else if (carta === 5) alert("El emperador: Estás en una posición de autoridad y liderazgo. Tienes la experiencia y el conocimiento para tomar decisiones y actuar. Eres organizado y estructurado, y tienes una visión clara de lo que quieres lograr. Puedes necesitar afirmar tu poder e influencia en alguna situación o relación.");
  else if (carta === 6) alert("El sumo sacerdote: Estás buscando orientación y consejo de una fuente o autoridad superior. Estás siguiendo un conjunto de reglas o tradiciones que han sido establecidas por otros. Eres respetuoso y obediente, y valoras la estabilidad y el orden. Puedes necesitar aprender más sobre tus creencias o valores, o buscar alguna guía espiritual o moral.");
  else if (carta === 7) alert("Los enamorados: Te enfrentas a una elección o un dilema que implica tu corazón o tus emociones. Puedes sentirte atraído por alguien o algo que te ofrece amor, pasión o placer. También puedes necesitar equilibrar tus deseos con tus responsabilidades o compromisos. Sigue tus sentimientos y confía en tu intuición.");
  else if (carta === 8) alert("El carro: Tienes el control de tu destino y dirección. Tienes la voluntad y la determinación para superar cualquier desafío u obstáculo que pueda surgir en tu camino. Eres seguro y ambicioso, y sabes cómo equilibrar tus fuerzas y energías. Puedes necesitar enfocarte en tus metas y mantenerte en el camino.");
  else if (carta === 9) alert("La justicia: Estás tratando con una situación que implica equidad, justicia o karma. Puedes necesitar enfrentarte a las consecuencias de tus acciones o decisiones, o resolver algún asunto legal o contractual. Eres honesto e imparcial, y buscas la verdad y el equilibrio en todas las cosas. Puedes necesitar sopesar tus opciones cuidadosamente y actuar con integridad.");
  else if (carta === 10) alert("El ermitaño: Estás en una fase de introspección y soledad. Buscas sabiduría y conocimiento desde dentro de ti mismo o desde otros que tienen más experiencia que tú. Eres humilde y discreto, y prefieres trabajar solo o en silencio. Puedes necesitar un tiempo alejado del ruido y las distracciones del mundo.");
  else if (carta === 11) alert("La rueda de la fortuna: Estás experimentando un cambio o una transición en tu vida que está más allá de tu control. Puedes enfrentarte a algunos altibajos, algunas ganancias y pérdidas, algunas oportunidades y desafíos. Eres adaptable y optimista, y aceptas los ciclos de la vida con gracia y gratitud. Puedes necesitar ir con la corriente y abrazar los cambios.");
  else if (carta === 12) alert("La fuerza: Tienes la fuerza y el coraje para enfrentar cualquier situación o desafío que pueda surgir en tu vida. Eres seguro y resiliente, y sabes cómo usar tu poder interno sabiamente. Eres compasivo y gentil, y sabes cómo domar tus impulsos o emociones. Puedes necesitar mostrar paciencia o perseverancia en alguna situación o relación.");
  else if (carta === 13) alert("El colgado: Estás en un estado de suspensión o sacrificio. Puedes necesitar dejar ir algo o alguien que te está frenando o limitando. Estás dispuesto a rendir tu ego o tus apegos por un propósito superior o un bien mayor. Puedes necesitar ver las cosas desde una perspectiva diferente o adoptar una nueva actitud.");
  else if (carta === 14) alert("La muerte: Estás pasando por una transformación o un final en algún aspecto de tu vida. Puedes necesitar cerrar un capítulo o decir adiós a algo o alguien que ya no te sirve. Estás listo para un nuevo comienzo o un renacimiento que te traerá crecimiento o renovación. Puedes necesitar abrazar el cambio y dejar ir el pasado.");
  else if (carta === 15) alert("La templanza: Estás en un estado de armonía y equilibrio. Has logrado una mezcla perfecta de opuestos o extremos en tu vida. Eres tranquilo y pacífico, y sabes cómo moderar tus acciones o emociones. Puedes necesitar practicar algún autocontrol o cooperación en alguna situación o relación.");
  else if (carta === 16) alert("El diablo: Te enfrentas a alguna tentación o adicción que afecta tu libertad o felicidad. Puedes estar obsesionado con algo o alguien que te ofrece placer, poder, o dinero, pero a un alto costo. Estás apegado o dependiente de algo que es poco saludable o dañino para ti. Puedes necesitar liberarte de tus cadenas o enfrentar tus miedos.");
  else if (carta === 17) alert("La torre: Estás experimentando un shock repentino o una interrupción en tu vida que está sacudiendo tus cimientos o creencias. Puedes enfrentarte a alguna crisis o conflicto que te obligará a cambiar o reconstruir algo que era estable o seguro para ti. Estás expuesto o vulnerable, pero también liberado de ilusiones o limitaciones. Puedes necesitar aceptar la realidad y aprender de la experiencia.");
  else if (carta === 18) alert("La estrella: Tienes esperanza y fe en el futuro después de superar algunas dificultades o desafíos en tu vida. Has encontrado tu propósito o dirección, y sigues tus sueños o aspiraciones. Eres optimista y generoso, y compartes tus dones o talentos con los demás. Puedes necesitar confiar en el universo y expresar tu gratitud.");
  else if (carta === 19) alert("La luna: Estás en un estado de confusión o ilusión. Puedes estar influenciado por tu subconsciente o emociones, o por algunos factores ocultos o desconocidos. Eres intuitivo e imaginativo, y exploras tus sueños o fantasías. Puedes necesitar enfrentar tus miedos o dudas, o buscar alguna claridad o verdad.");
  else if (carta === 20) alert("El sol: Estás en un estado de alegría y felicidad. Has logrado el éxito o el reconocimiento, y disfrutas de los frutos de tus esfuerzos. Eres radiante y confiado, y difundes tu calidez o positividad. Puedes necesitar celebrar tus logros, o compartir tu felicidad con otros.");
  else if (carta === 21) alert("El juicio: Estás en un estado de despertar o juicio. Has llegado a una conclusión o decisión, y enfrentas las consecuencias de tus acciones. Eres consciente y responsable, y te alineas con tu yo superior o propósito. Puedes necesitar evaluar tu situación, o hacer algunos cambios en tu vida.");
  else if (carta === 22) alert("El mundo: Has completado un ciclo o meta en tu vida. Has alcanzado el cumplimiento o la satisfacción, y disfrutas de las recompensas de tus esfuerzos. Eres integrado y equilibrado, y tienes una sensación de plenitud o completitud. Puedes necesitar reconocer tu éxito, o iniciar un nuevo viaje.");  
  else if (carta === 0) alert("Gracias por jugar");
}while ( carta != 0)